export const GET_TEST: string = "GET_TEST";
export const GET_VETERINARIAN: string = "GET_VETERINARIAN";
export const GET_OWNER: string = "GET_OWNER";
export const GET_PUPPY: string = "GET_PUPPY";
export const REGISTER_VETERINARIAN = "REGISTER_VETERINARIAN";
export const REGISTER_OWNER = "REGISTER_OWNER";
export const REGISTER_PUPPY = "REGISTER_PUPPY";
export const GENERAL_REQUEST = "GENERAL_REQUEST";
export const ADD_VACCINE = "ADD_VACCINE";